### ISSUE TITLE
Can I fork and change this?

### ISSUE THREAD

**Issue by RaitaroH** [hkbakke/bash-insulter#11]
@hkbakke I don't see any license so... I have to ask. Can I make a version of this where the bash doesn't insult you but instead is saying nice things?

**Comment by RaitaroH** [comment]
Also what license to add? Or not add anything, if given the permission to fork?

**Comment by hkbakke** [comment]
Hi, I added a license to the project. Just go and have fun with it!

However, I just added the possibility to configure your own messages using CMD_NOT_FOUND_MSGS and CMD_NOT_FOUND_MSGS_APPEND as documented in the README, withouth having to change the source code at all. Perhaps this will solve your problem without having to write your own version!

**Comment by RaitaroH** [comment]
Nice. Thanks. In my case I kinda want to have an anime girl bash sorta thing, so I will see.
