### ISSUE TITLE
Works every third time 

### ISSUE THREAD

**Issue by mutantkeyboard** [hkbakke/bash-insulter#19]
Using this on Debian 9. 
However, the script seems to work only every 3rd time. 
I didn't tinker too much around the script though. If I find the solution meanwhile, I'll send you a pull request. 

![2018-02-27 18_52_43-virtualbox](https://user-images.githubusercontent.com/1167494/36745518-0bd655a0-1bf0-11e8-9950-21922740f559.png)

**Comment by Plloi** [comment]
That's somewhat intended, though in the long run it should average out to every other.
See: https://github.com/hkbakke/bash-insulter/blob/e83e6d4ae12d252c23a703dc36294ad3177a20f3/src/bash.command-not-found#L78

**Comment by hkbakke** [comment]
As @Plloi said, this is by design. I know I would disable bash-insulter very quickly if it interfered every single time.

**Comment by Plloi** [comment]
Got to thinking... is there interest in being able to adjust frequency?

**Comment by mutantkeyboard** [comment]
That's actually a very good question @Plloi
