### ISSUE TITLE
[Suggestion] Add sudoers insults

### ISSUE THREAD

**Issue by 132ikl** [hkbakke/bash-insulter#2]
You could add the insults from sudoers. They're in sudo/plugins/sudoers/. Here they are in a targz:
https://filesha.re/sudoers.tar.gz

**Comment by hkbakke** [comment]
Hi

I am not comfortable with just taking the sudo insults, and I also think it is fun with different insults on a system where both are activated. 

However, to make it easy for you to include your own insults/messages without having to change the source code I added a couple of environment variables that you can configure in the form of CMD_NOT_FOUND_MSGS and CMD_NOT_FOUND_MSGS_APPEND as documented in the README.
