### ISSUE TITLE
Installation didn't work

### ISSUE THREAD

**Issue by twifty** [hkbakke/bash-insulter#24]
As per the install method in the README, I copied:
```
if [ -f /etc/bash.command-not-found ]; then
    . /etc/bash.command-not-found
fi
```
to `~/.bashrc` and the sources to the `/etc` directory. Restarted my terminal (logout is not required) and it didn't work. I changed the above to:
```
if [[ -f /etc/bash.command-not-found ]]; then # Note the double brackets
    . /etc/bash.command-not-found
fi
```
restarted terminal and it does. Note, a one-liner can also be used
```
[[ -f /etc/bash.command-not-found ]] && . /etc/bash.command-not-found
```

Also, why do you recommend adding the file to `/etc/`, wouldn't it be safer (no sudo required) to add to `~/` (at least suggest it in the README)?

**Comment by hkbakke** [comment]
Double brackets is a bash, and ksh, thing. Single brackets is POSIX compatible and supported by the typical default shell dash (which /bin/sh points to) on many modern distributions. Strange that it did not work for you however, as even with bash single and double brackets should give the same result in that particular case. I really do not have any explanation without knowing more.

As for putting it in /etc it is to make it available globally, which makes sense for a system administrator to enable it for ordinary users. If you are the only user of the system or you want to enable it only for your self it would make more sense to put it in your home directory as you suggest.

**Comment by twifty** [comment]
My default shell is bash. It's also not the first time I've seen this problem, I've had to edit many makefiles for the exact same reason.

Just tried a simple script
```
#!/bin/bash
if [ -f /etc/passwd ] 
then
   echo "Yes"
else
  echo "No"
fi 
```
Which works as expected. Must be something wrong on my system.
